title: Wormser Linux User Stammtisch
email: wolust@untergang.de
author: Stefan Höhn
description: Der Wormser Linux User Stammtisch trifft sich jeden 1. Dienstag im Monat
baseurl: ''
url: 'https://wolust.de'
date_format_day: '%-d .'
date_format_year: '%Y'
date_format : '%-d . %m . %Y %H:%M'
header_pages:
  - map.md
  - help.md
google_verification: 'fdVYZrBjcMeFQK5MnFi4WhNe3-RVaVgjMZvh6ekvItM'
google_analytics: null
google_tag_manager: null
bing_verification: null
animated: true
show_related_posts: false
show_post_footers: false
show_social_icons: true
ajaxify_contact_form: true
enable_mathjax: false
extended_fonts: true
enable_anchorjs: true
post_preview_image: true
fb_page: false
fb_page_id: null
disqus_shortname: null
txtpen_sitename: null
facebook_comments: null
facebook_appid: null
facebook_comments_number: 10
github_username: wolust
reddit_username: null
bitbucket_username: null
stackoverflow_id: null
twitter_username: wolug
skype_username: null
steam_nickname: null
google_plus_id: null
linkedin_username: null
angellist_username: null
medium_id: null
bitcoin_url: null
paypal_url: null
flattr_button: null
telegram_username: null
vk_id: null
show_sharing_icons: false
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true
text:
  pagination:
    newer: Neuer
    older: Älter
  share_buttons:
    text: Teile diese Webseite!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Geändert
    minute_read: Min. Lesezeit
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: lolo98?
    subject: New submission!
    submit: Sag Hallo !
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: de_DE
markdown: kramdown
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data
permalink: pretty
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

